version: "3.8"
services:
  proxy:
    container_name: nginx-proxy
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    container_name: postgres-db
    image: postgres
    # restart: always
    ports:
      - 5432:5432
    volumes:
      - postgre-db:/var/lib/postgresql/data
      - /db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: kodesonik
      POSTGRES_PASSWORD: azertyui

    # networks:
    #   default:
    #     ipv4_address: 172.20.0.10
  
  cache:
    container_name: redis-cache
    image: redis
    ports:  
      - 6379:6379
    # restart: always
    # networks:
    #   default:
    #     ipv4_address: 172.20.0.12
      
  adminer:
    container_name: adminer 
    image: adminer
    # restart: always
    ports:
      - 8080:8080
    # networks:
    #   default:
    #     ipv4_address: 172.20.0.11

volumes:
  postgre-db: 
    driver: local

# networks:
#   default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16
#           gateway: 172.20.0.1
#           aux_addresses:
#             adminer: 172.20.0.11
#             db: 172.20.0.10
#             cache: 172.20.0.12
